### ISSUE TITLE
Commutative ops as static methods and non-commutative ops as instance methods

### ISSUE THREAD

**Issue by bathos** [Ginden/set-methods#1]
It seems more expressive and better organized to me to call:

```
Set.union(setA, setB)
```

than

```
setA.union(setB)
```

...because this is a commutative op. It "means" nothing that I am calling it on one of these sets rather than the other. Contrast with a non-commutative op like `setA.subtract(setB)`; here when we call the instance method it has "meaning," it does something relative to that instance specifically.

The case for commutative ops being static is maybe better illustrated by examples with more than two sets -- especially if you consider cases where one is trying to work with arrays of sets in the abstract:

```
sets[0].union(...sets.slice(1));
// vs
Set.union(...sets);
```

**Comment by Ginden** [comment]
`sets[0].union(...sets.slice(1));` yields the same result as `new Set().union(...sets)`
Going further, `new Set().union(...foo)` would be the same as yours `Set.union(...foo)`, saving virtually 6 characters for similar readability.

> here when we call the instance method it has "meaning," it does something relative to that instance specifically.

Your point is invalid here, because instance HAS meaning because of subclassing. Imagine that we want to have `[HashSet](https://docs.oracle.com/javase/8/docs/api/java/util/HashSet.html)`... If we implement methods as static, end-user will be required to stay aware of library implementation details.

**Comment by bathos** [comment]
True, the `new Set` technique would work the same, certainly, though the point there was not so much readability as to be able to write generic pipelines without jumping through unnatural hoops; the example highlights (I think) that it is not the natural place for the function to live.

Can you clarify on that last point? I don't understand why a static method is an "implementation detail" and an instance method is not.

**Comment by Ginden** [comment]
> Can you clarify on that last point? I don't understand why a static method is an "implementation detail" and an instance method is not.

Assume we have class `TypedSet`.

```javascript
class StringSet extends Set {
     add(val) {
          if(typeof val !== 'string') throw new TypeError();
          return super.add(val);
     }
}```

Then, consider following code:
```
const foo = new StringSet();
foo.union([1,2,3]); // throws - adding element to StringSet instance always require type check
foo.union(['bar']); // works properly
Set.union(foo, [1,2,3]); // will result in Set instance, instead of StringSet instance; can cause subtle bugs later
StringSet.union(foo, [1,2,3]); // will result in StringSet instance. User have to be aware that he need StringSet, not superclass not derived class (like LongStringSet or ShortStringSet).
```

**Comment by bathos** [comment]
I understand the problem you've described, though the behavior there is what Id expect (c.f. `Array.from`). However, users will need to be just as aware of what classes / subclasses they're dealing with when using instance methods; really, that problem has little to do with static vs instance I think:

```
const foo = new StringSet();
const bar = new Set();
foo.union(bar); // instanceof StringSet
bar.union(foo); // instanceof Set
```

AFAICT there's really no solution to that particular gotcha that doesn't involve the consumer needing express knowledge of the classes they're dealing with.

In any case, thanks for reviewing the idea. Maybe others might weigh in -- given that organization patterns for classes have an unavoidable subjective facet, and assuming the goal is to find the API which is intuitive to the widest spread of people, it may well be that the current approach satisfies that goal best, but the two of us don't make a great sample size. :)

**Comment by pitaj** [comment]
IMO every prototype method should have a corresponding static method. prototype methods could be implemented as shortcuts for static methods. For example:

```js
function union(...iterables) {
    const first = iterables[0];
    const subConstructor = isSet(first) ? getSpeciesConstructor(first) : Set;
    const ret = new subConstructor();
    for (const _set of iterables) {
        for (const element of _set) {
            ret.add(element);
        }
    }
    return ret;
}
Set.union = union;
Set.prototype.union = function (...iterables) {
  return union(this, ...iterables);
};
```

**Comment by Ginden** [comment]
I believe that's a bit out of scope - to make this happen, Arrays should have the same behaviour.
