### ISSUE TITLE
Accept single arguments, or accept many arguments?

### ISSUE THREAD

**Issue by domenic** [Ginden/set-methods#11]
Right now the spec demands you do `set1.union(...set2)` instead of `set1.union(set2)`. This is unexpected from how the terms union, intersection, set difference, and symmetric difference are used in set theory.

**Comment by Ginden** [comment]
@domenic Are you sure? When I wrote the spec it used argument name `iterables` and for me it looks like it accepts arbitrary number of iterables.

**Comment by Ginden** [comment]
> The argument names are always "...items".

@gsathya decided for consistency in this case. 

> But you're right that union() falls into the category of arbitrary number of iterables per the spec text. Whether it should is another question...

Feel free to open issue. When I wrote spec and [section in README](https://github.com/Ginden/set-methods#union-intersect-etc-desired-signature) I preferred multiple iterables approach, but now I would rather pick single iterable as argument to `union` and other set-theoretic methods.
