### ISSUE TITLE
Should this proposal be split into two?

### ISSUE THREAD

**Issue by gsathya** [Ginden/set-methods#14]
This proposal could potentially be split into two 
(1) Set specific methods like union, intersection, difference, symmetricDifference
(2) Methods copies over from Array like map, filter, etc

Reasons to do the split:
(a) The latter proposal could potentially add the Array methods to all collections, not just Sets. It's kinda confusing to add all these methods to Sets first and not other collections.
(b) @ljharb mentioned that these Array methods could potentially be implemented using the upcoming [protocols proposal](https://github.com/michaelficarra/proposal-first-class-protocols) for all the collections, not just Sets.

Reasons to not do the split:
(a) @domenic had concerns like #10 which could affect both the proposals -- like union vs addAll.
(b) It's confusing to have many similar proposals (.. especially looking at the complexity around the various proposals of class fields)

Alternatively -- we could add all the array methods to Maps in this proposal.

**Comment by ljharb** [comment]
I would be very concerned about advancing Set methods without similar Map methods, fwiw.

**Comment by gsathya** [comment]
Committee suggested that we split this proposal into two:
(1)  A proposal with set specific with methods
(2) A proposal with general collection methods (like the ones present in Array)
