### ISSUE TITLE
Please add .pop()

### ISSUE THREAD

**Issue by tabatkins** [Ginden/set-methods#18]
Popping from a Set/Map is actually *very* useful, regardless of whether there's a direction/ordering or not.  The semantics are just "remove one arbitrary value from the set and give it to me", which is annoyingly clumsy to implement by hand.

I've used `.pop()` in Python several times, and felt the lack of it in JS projects.

**Comment by Ginden** [comment]
This issue was moved to Ginden/collection-methods#1
