### ISSUE TITLE
"relativeComplement" is opposite direction to similar ops in other languages

### ISSUE THREAD

**Issue by tabatkins** [Ginden/set-methods#2]
The `.relativeComplement()` operation, when called like `A.rC(B)`, returns a set with all the elements of B that are *not* in A.  This is the opposite direction of the similar `minus()` method in Python, which returns the elements of A that aren't in B.

As well, `minus` has useful directionality built in - just by reading it, you can intuitively tell which set's items will be retained and which won't.  `relativeComplement` doesn't have this same intuition.

**Comment by Ginden** [comment]
Good point, I will update accordingly.

**Comment by Ginden** [comment]
It seems like Venn diagram is not obvious. Intended behaviour is of course: `(new Set([1,2,3])).minus([1,2]) // Set([3])` and that's how polyfill works.

I changed name of `relativeComplement` to `subtract` to match Immutable.js name here (and it's as expressive as `minus` name).

**Comment by tabatkins** [comment]
👍
