### ISSUE TITLE
`.flatMap` / `.flatten`

### ISSUE THREAD

**Issue by pitaj** [Ginden/set-methods#4]
https://github.com/tc39/proposal-flatMap

Seems like if `Set` has `.map`, it should also have `.flatMap` and `.flatten` like Arrays. The current Array proposal has them only working on Arrays and Array-like objects with @@ConcatSpreadable, so I'd say that if they are implemented on Sets, they should only work with Sets.

**Comment by Ginden** [comment]
I would update spec if `Array#flat{map,ten}`advance to stage 3/4.
