### ISSUE TITLE
What's the motivation for isSet?

### ISSUE THREAD

**Issue by gsathya** [Ginden/set-methods#5]
Generally there is really no brand checking in JavaScript (except for isArray, which I've heard was a mistake). What's the motivation for Set.isSet?

**Comment by Ginden** [comment]
@gsathya It was added as analog for Array.isArray and it's featured in many libraries adding Sets (eg. Immutable.js). Though, I'm not emotionally attached to it.

**Comment by gsathya** [comment]
What's the main use case for this? Array.isArray was mainly added for concat and consistency reasons. isSet fits better with the [Builtins.is](https://github.com/jasnell/proposal-istypes) proposal, IMO.

**Comment by Ginden** [comment]
@gsathya Removed in ec18256
