### ISSUE TITLE
Naming bikeshed: add/removeElements

### ISSUE THREAD

**Issue by domenic** [Ginden/set-methods#9]
Sets use `delete`, not `remove`.

`add()` and `delete()` also add/delete elements. I think the name should be more explicit. I'd suggest `addAll`/`deleteAll` perhaps.

**Comment by ljharb** [comment]
Would it be web incompatible to make add and delete start taking multiple arguments?

**Comment by domenic** [comment]
My guess is yes because of code like `arr.forEach(set.add, set)`.

**Comment by Ginden** [comment]
Done.
